spring:
  profiles:
    active: dev
    include: oauth


#  session:
#    jdbc:
#      initialize-schema: always
#    store-type: jdbc
server:
  error:
    include-exception: true
    include-stacktrace: always

